### ISSUE TITLE
Remove redundancy in ONB constructor

### ISSUE THREAD

**Issue by ziotom78** [ElisaLegnani/PhotorealisticRendering#15]
In the branch `pathtracing`, there are two implementations of `ONB::ONB` ([lines 222–257 in geometry.h](https://github.com/ElisaLegnani/PhotorealisticRendering/blob/pathtracing/include/geometry.h#L222-L257)), which are essentially the same but accept either a `Vec` or a `Normal`.

It would be better to create a constructor that takes the three parameters `x`, `y`, and `z`:

```c++
class ONB {
    // …
    ONB(float x, float y, float x) {
        // Put here your implementation of the OBN algorithm
    }
    // …
};
```

and then call it from the other two constructors:

```c++
class ONB {
    // …
    ONB(Vec normal) : ONB{normal.x, normal.y, normal.z} {}
    ONB(Normal normal) : ONB{normal.x, normal.y, normal.z} {}
};
```

In this way you have just one implementation of the algorithm and it is easier to catch bugs.

**Comment by adelezaini** [comment]
Thank you for the enhancement suggestion. We fixed the issue as recommended. 
Please do not hesitate to report any other bugs or feature requests! We would be pleased...
